meta_product_name : « MangoGather »

meta_title : « Mango, l’ingrédient manquant pour sublimer ton quotidien ! »

meta_description : « MangoGather est une appli d'entre-aide entre utilisateur. »

meta_image : "logo.png"

# twitter_account: “@product_twitter_account”
